apiVersion: v1
entries:
  resource-provisioning:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-05-15T11:28:31.168453968+02:00"
    description: A Helm chart for Kubernetes
    digest: 1b4f2871c9c5eb4781dcae4550b18698a6982e5c910f29ff4a8f8f436de4fd88
    name: resource-provisioning
    type: application
    urls:
    - resource-provisioning-1.0.0.tgz
    version: 1.0.0
generated: "2024-05-15T11:28:31.166696616+02:00"
